backend:
  name: github
  repo: marianoboragno/marianoboragno.github.io
  branch: main

# Dónde guarda Sveltia las imágenes en el repositorio
media_folder: "public/assets/img"
# Qué ruta escribe en el Markdown para que el navegador la encuentre
public_folder: "/assets/img"

# Colecciones de contenido
collections:
  - name: "noticias_puyo"
    label: "Mercedes News"
    folder: "src/content/noticias_puyo"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "markdown", buttons: ["bold", "italic"] }
      - { label: "Fecha", name: "date", widget: "datetime" }
      - { label: "Imagen Destacada", name: "thumbnail", widget: "image", required: false }
      - { label: "Cuerpo de la Noticia", name: "body", widget: "markdown" }
